-- V4: Seed Indian tourist destinations
INSERT INTO destinations (name, state, description, short_description, image_url, season, avg_cost_2d_1n_inr, travel_experience, local_food, nearby_attractions, latitude, longitude, popularity_score, is_featured) VALUES

-- RAJASTHAN
('Jaipur', 'Rajasthan', 'Jaipur, the Pink City and capital of Rajasthan, is a UNESCO World Heritage city renowned for its stunning Mughal and Rajput architecture. The majestic Amber Fort, the intricate Hawa Mahal (Palace of Winds), and the astronomical Jantar Mantar are must-sees. The citys bustling bazaars offer exquisite textiles, blue pottery, and precious gemstones.', 'The Pink City of palaces, forts, and vibrant bazaars.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Hawa_Mahal_Jaipur.jpg/1280px-Hawa_Mahal_Jaipur.jpg', 'WINTER,ALL_SEASON', 5500, 'Heritage & Cultural', '["Dal Baati Churma","Laal Maas","Pyaaz Kachori","Ghevar","Masala Chai"]', '["Amber Fort (11km)","Nahargarh Fort (16km)","Chand Baori (95km)","Sariska Tiger Reserve (107km)"]', 26.9124, 75.7873, 9.4, TRUE),

('Jaisalmer', 'Rajasthan', 'The Golden City rises dramatically from the Thar Desert with its honey-coloured sandstone fort and intricately carved havelis. Jaisalmer Fort is a living fort where people still reside within its ancient walls. The Sam Sand Dunes offer thrilling camel safaris and magical desert sunsets under a blanket of stars.', 'A sand-castle city glowing gold in the Thar Desert.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Jaisalmer_fort_sunset.jpg/1280px-Jaisalmer_fort_sunset.jpg', 'WINTER,ALL_SEASON', 4500, 'Desert Adventure & Heritage', '["Dal Baati Churma","Ker Sangri","Gatte ki Sabzi","Mirchi Bada","Camel Milk Chai"]', '["Sam Sand Dunes (40km)","Gadisar Lake (2km)","Patwon ki Haveli (1km)","Kuldhara Ghost Village (18km)"]', 26.9157, 70.9083, 9.1, TRUE),

('Udaipur', 'Rajasthan', 'Called the City of Lakes, Udaipur is perhaps the most romantic city in India. Surrounded by the Aravalli hills and adorned with shimmering lakes, ornate palaces, and vibrant bazaars. The Lake Palace hotel sitting in the middle of Lake Pichola looks like it is floating on water.', 'The City of Lakes — Rajasthan most romantic destination.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Lake_Palace_Udaipur.jpg/1280px-Lake_Palace_Udaipur.jpg', 'WINTER,ALL_SEASON', 6000, 'Romantic & Heritage', '["Dal Baati","Mawa Kachori","Daal Baati","Rabri","Banjara Thali"]', '["Lake Palace","City Palace","Sajjangarh Monsoon Palace","Kumbalgarh Fort (84km)"]', 24.5854, 73.7125, 9.3, TRUE),

('Jodhpur', 'Rajasthan', 'The Blue City of Jodhpur is dominated by the mighty Mehrangarh Fort, one of the largest forts in India, perched 400 feet above the city. The blue-painted houses of the Brahmin quarter below give the city its iconic color. The bazaars around the clock tower are perfect for silver jewelry and handicrafts.', 'India Blue City dominated by a magnificent hilltop fort.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Jodhpur_03-2016_img01.jpg/1280px-Jodhpur_03-2016_img01.jpg', 'WINTER,ALL_SEASON', 4000, 'Cultural & Photography', '["Mirchi Vada","Mawa Lassi","Gatte ki Sabzi","Pyaaz Kachori","Lapsi"]', '["Mehrangarh Fort","Umaid Bhawan Palace","Jaswant Thada","Mandore Gardens (9km)"]', 26.2389, 73.0243, 8.8, FALSE),

('Ranthambore', 'Rajasthan', 'Ranthambore National Park is one of Indias finest tiger reserves and the best place in India to spot wild tigers. The park contains the ruins of a 10th-century fort, giving a dramatic backdrop to wildlife sightings. Jeep safaris at sunrise and sunset offer the best chances of spotting Bengal tigers, leopards, and crocodiles.', 'Indias best tiger reserve with dramatic fort ruins.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Ranthambore_Tiger.jpg/1280px-Ranthambore_Tiger.jpg', 'WINTER', 8000, 'Wildlife Safari', '["Laal Maas","Dal Baati","Jungle Thali","Ker Sangri"]', '["Ranthambore Fort","Padam Lake","Malik Talao","Kachida Valley"]', 26.0173, 76.5026, 8.9, FALSE),

-- KERALA
('Munnar', 'Kerala', 'Munnar is a breathtaking hill station nestled at the confluence of three mountain streams in the Western Ghats. Vast stretches of tea plantations carpet the rolling hills in shades of emerald green. The region is home to the rare Neelakurinji flower that blooms once every 12 years, turning entire hillsides blue-purple.', 'Emerald tea-carpeted hills in the heart of Western Ghats.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Munnar_Kerala.jpg/1280px-Munnar_Kerala.jpg', 'ALL_SEASON', 5000, 'Hill Station & Nature', '["Puttu and Kadala Curry","Appam with Stew","Kerala Parotta","Fish Molee","Chaya (Tea)"]', '["Eravikulam National Park","Mattupetty Dam","Top Station","Attukad Waterfalls"]', 10.0889, 77.0595, 9.0, TRUE),

('Alleppey', 'Kerala', 'Alleppey, known as the Venice of the East, is famous for its serene network of backwaters, lagoons, and canals. Staying in a traditional kettuvallam (houseboat) drifting through the backwaters past rice paddies and coconut groves is a quintessential Kerala experience. The town also hosts the famous Nehru Trophy Boat Race.', 'The Venice of the East — Kerala iconic backwater paradise.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Kerala_backwaters.jpg/1280px-Kerala_backwaters.jpg', 'ALL_SEASON', 7500, 'Houseboat & Backwaters', '["Karimeen Pollichathu","Prawn Moilee","Kappa Biriyani","Appam","Coconut Ladoo"]', '["Nehru Trophy Race Venue","Marari Beach (14km)","Alappuzha Lighthouse","Krishnapuram Palace (47km)"]', 9.4981, 76.3388, 9.2, TRUE),

('Wayanad', 'Kerala', 'Wayanad is a lush green district perched on the slopes of the Western Ghats, famous for its wildlife sanctuaries, spice plantations, and ancient tribal culture. The Chembra Peak trek offers stunning views of misty valleys. Edakkal Caves feature prehistoric petroglyphs dating back over 8,000 years.', 'Misty green highlands with wildlife, spices, and ancient caves.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Chembra_Peak.jpg/1280px-Chembra_Peak.jpg', 'MONSOON,ALL_SEASON', 4500, 'Nature & Trekking', '["Bamboo Biriyani","Kaalan","Puttu","Wild Honey","Banana Chips"]', '["Chembra Peak","Edakkal Caves","Banasura Sagar Dam","Muthanga Wildlife Sanctuary"]', 11.6854, 76.1320, 8.5, FALSE),

('Kovalam', 'Kerala', 'Kovalam is a small coastal town near Thiruvananthapuram with beautiful crescent-shaped beaches. Lighthouse Beach is the most popular, with its iconic red-and-white striped lighthouse. The calm waters make it ideal for swimming, while Ayurvedic massage centers and seafood shacks line the shore.', 'Crescent beaches with lighthouse views and Ayurvedic wellness.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Kovalam_beach_lighthouse.jpg/1280px-Kovalam_beach_lighthouse.jpg', 'WINTER', 5500, 'Beach & Wellness', '["Fish Curry Rice","Lobster Fry","Kerala Prawn","Coconut Water","Banana Fritters"]', '["Lighthouse Beach","Hawa Beach","Vizhinjam Rock Cave Temple","Padmanabhapuram Palace (52km)"]', 8.3988, 76.9784, 8.7, FALSE),

('Thekkady', 'Kerala', 'Thekkady is home to the Periyar Wildlife Sanctuary, one of Indias most visited protected areas. A boat ride on Periyar Lake is the best way to spot elephants, sambar deer, and exotic birds at the water edge. The surrounding hills are blanketed with spice plantations of cardamom, pepper, and cinnamon.', 'Spice-scented hills encircling a wildlife-rich lake sanctuary.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Periyar_lake_thekkady.jpg/1280px-Periyar_lake_thekkady.jpg', 'ALL_SEASON', 6000, 'Wildlife & Spice Trails', '["Cardamom Tea","Bamboo Rice","Vine Pepper Chicken","Coconut Fish Curry","Jackfruit Halwa"]', '["Periyar Lake Boat Ride","Spice Plantation Tour","Elephant Junction","Mangaladevi Temple"]', 9.5993, 77.1620, 8.6, FALSE),

-- HIMACHAL PRADESH
('Manali', 'Himachal Pradesh', 'Manali is a high-altitude Himalayan resort town and one of Indias most popular adventure destinations. Rohtang Pass offers stunning snow views accessible by road. The ancient Hadimba Temple sits in a cedar forest. The town is a gateway for treks to Beas Kund, Hampta Pass, and the remote Lahaul-Spiti valley.', 'Himalayan adventure hub with snow peaks, rivers, and ancient temples.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Manali_valley.jpg/1280px-Manali_valley.jpg', 'SUMMER', 7000, 'Adventure & Snow', '["Sidu Bread","Dham Thali","Chha Gosht","Trout Fish","Aktori Cake"]', '["Rohtang Pass","Solang Valley","Hadimba Devi Temple","Old Manali Village"]', 32.2396, 77.1887, 9.3, TRUE),

('Shimla', 'Himachal Pradesh', 'Shimla, the former summer capital of British India, retains a charming colonial ambiance with its Victorian architecture, toy train (a UNESCO World Heritage Route), and the famous Mall Road flanked by colonial-era buildings. Snow-capped peaks, apple orchards, and cedar forests surround this picturesque hill town.', 'Colonial charm and apple orchards in Himalayan foothills.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Shimla_city_view.jpg/1280px-Shimla_city_view.jpg', 'ALL_SEASON', 5500, 'Hill Station & Colonial Heritage', '["Siddu","Dham","Babru","Chha Meat","Apple Juice"]', '["Mall Road","Jakhu Temple","Kufri (16km)","Kalka-Shimla Toy Train"]', 31.1048, 77.1734, 9.0, TRUE),

('Spiti Valley', 'Himachal Pradesh', 'Spiti Valley is a remote cold desert mountain valley at an altitude of 12,500 feet in the Himalayas. Often called Little Tibet, it features ancient Buddhist monasteries (Key Monastery, Dhankar), dramatic lunar landscapes, and some of the clearest skies for stargazing in India. Roads are open only from June to September.', 'Remote Himalayan cold desert with ancient Buddhist monasteries.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Key_Monastery_Spiti.jpg/1280px-Key_Monastery_Spiti.jpg', 'SUMMER', 9000, 'Remote Adventure & Spirituality', '["Butter Tea","Tsampa","Thukpa","Yak Cheese","Chhang Barley Beer"]', '["Key Monastery","Dhankar Lake","Chandratal Lake","Kibber Village"]', 32.2461, 78.0336, 8.8, FALSE),

('Dharamshala', 'Himachal Pradesh', 'Dharamshala is the seat of the Tibetan government-in-exile and home to the Dalai Lama. Upper Dharamshala (McLeod Ganj) is a vibrant hub of Tibetan culture, Buddhist monasteries, and spectacular Himalayan trekking. The town blends Indian and Tibetan cultures seamlessly around tranquil temples and peaceful cafes.', 'Tibet meets Himachal — home of the Dalai Lama and mountain treks.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Mcleod_Ganj_Himachal.jpg/1280px-Mcleod_Ganj_Himachal.jpg', 'ALL_SEASON', 4500, 'Spiritual & Trekking', '["Thukpa","Momos","Butter Tea","Tsampa","Tibetan Bread"]', '["Namgyal Monastery","Bhagsunag Waterfall","Triund Trek","Dal Lake"]', 32.2190, 76.3234, 8.7, FALSE),

-- GOA
('North Goa', 'Goa', 'North Goa is the vibrant, energetic face of Goa with iconic beaches like Calangute, Baga, and Anjuna. The region comes alive at night with beach shacks, live music, and flea markets. Portuguese-era churches, spice plantations, and the UNESCO-listed Old Goa basilicas are within easy reach inland.', 'Vibrant beaches, nightlife, and Portuguese heritage in India western coast.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Baga_Beach_Goa.jpg/1280px-Baga_Beach_Goa.jpg', 'WINTER', 6500, 'Beach & Nightlife', '["Goan Fish Curry","Prawn Balchao","Bebinca","Feni","Vindaloo"]', '["Calangute Beach","Baga Beach","Anjuna Flea Market","Basilica of Bom Jesus"]', 15.5492, 73.7620, 9.1, TRUE),

('South Goa', 'Goa', 'South Goa offers a quieter, more luxurious side of Goa with pristine beaches like Palolem and Colva, luxury resorts, and a relaxed atmosphere. The region retains its traditional Goan character with quaint villages, old churches, and spice farms. Palolem Beach is consistently rated one of the most beautiful beaches in India.', 'Serene beaches and luxury retreats — the quieter side of Goa.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Palolem_beach_south_goa.jpg/1280px-Palolem_beach_south_goa.jpg', 'WINTER', 7000, 'Beach & Relaxation', '["Xacuti Curry","Prawn Rawa Fry","Crab Xec Xec","Sol Kadi","Cornna"]', '["Palolem Beach","Colva Beach","Dudhsagar Falls (60km)","Cabo de Rama Fort"]', 15.0100, 74.0232, 8.9, FALSE),

('Dudhsagar Falls', 'Goa', 'Dudhsagar (Sea of Milk) is a four-tiered waterfall on the Mandovi River on the Goa-Karnataka border, and one of Indias tallest waterfalls at 310 meters. The cascading milk-white waters against the lush green Bhagwan Mahavir Wildlife Sanctuary background make for a spectacular sight, especially during and after the monsoon.', 'One of India tallest waterfalls surging through dense jungle.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Dudhsagar_Falls.jpg/1280px-Dudhsagar_Falls.jpg', 'MONSOON', 4000, 'Nature & Waterfalls', '["Jungle Jhol","Goan Chai","Coconut Water","Corn","Local Cashew Snacks"]', '["Bhagwan Mahavir Wildlife Sanctuary","Mollem National Park","Tambdi Surla Temple"]', 15.3143, 74.3141, 8.5, FALSE),

-- UTTARAKHAND
('Rishikesh', 'Uttarakhand', 'Rishikesh, the Yoga Capital of the World, sits at the foothills of the Himalayas on the banks of the holy Ganges River. It is the adventure sports hub of India (white-water rafting, bungee jumping, zip-lining) and the spiritual heart of yoga and meditation. The iconic Laxman Jhula suspension bridge and evening Ganga Aarti are unmissable.', 'Yoga capital of the world with adventure sports on the holy Ganges.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Rishikesh_Lakshman_Jhula.jpg/1280px-Rishikesh_Lakshman_Jhula.jpg', 'ALL_SEASON', 4000, 'Spiritual & Adventure', '["Aloo Puri","Kachori Sabzi","Lassi","Chaat","Thali (Sattvic)"]', '["Laxman Jhula","Ganga Aarti at Triveni Ghat","Beatles Ashram","Neelkanth Mahadev Temple"]', 30.0869, 78.2676, 9.2, TRUE),

('Nainital', 'Uttarakhand', 'Nainital is a charming lake town nestled in the Kumaon Himalayas, built around the beautiful Naini Lake. The town is surrounded by lush green hills with viewpoints like Snow View and Tiffin Top offering panoramic mountain vistas. Boating on Naini Lake at sunset with the town lights reflecting in the water is magical.', 'Himalayan lake town with panoramic mountain views.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Naini_Lake_Nainital.jpg/1280px-Naini_Lake_Nainital.jpg', 'SUMMER', 5500, 'Hill Station & Lakes', '["Bal Mithai","Singori","Aloo ke Gutke","Bhaang ki Chutney","Kafuli"]', '["Naini Lake","Snow View Point","Tiffin Top","Bhimtal Lake (22km)"]', 29.3919, 79.4542, 8.8, FALSE),

('Valley of Flowers', 'Uttarakhand', 'The Valley of Flowers National Park is a UNESCO World Heritage Site in the West Himalayan region of Uttarakhand. During the monsoon, the valley transforms into a breathtaking carpet of hundreds of species of alpine wildflowers including brahma kamal, blue poppies, and orchids against a backdrop of snow-capped Himalayan peaks.', 'A UNESCO-listed Himalayan valley that blooms into a wildflower paradise.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Valley_of_flowers_uttarakhand.jpg/1280px-Valley_of_flowers_uttarakhand.jpg', 'MONSOON', 6000, 'Trekking & Nature', '["Jhangora Kheer","Aloo Gutke","Mandua Roti","Local Dham","Rhododendron Juice"]', '["Hemkund Sahib (6km from base)","Ghangaria Base Camp","Nanda Devi National Park"]', 30.7283, 79.6059, 9.0, FALSE),

-- TAMIL NADU
('Madurai', 'Tamil Nadu', 'Madurai is one of the oldest continuously inhabited cities in the world and the cultural capital of Tamil Nadu. The Meenakshi Amman Temple, with its towering gopurams covered in thousands of sculpted deities, is one of the finest examples of Dravidian temple architecture. The city is alive with pilgrims, jasmine sellers, and silk weavers.', 'One of India oldest cities, dominated by the magnificent Meenakshi Temple.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Madurai_Meenakshi_Amman_Temple.jpg/1280px-Madurai_Meenakshi_Amman_Temple.jpg', 'ALL_SEASON', 3500, 'Temple & Cultural Heritage', '["Jigarthanda","Kari Dosa","Parottas with Salna","Mutton Seeraga Samba Biryani","Filter Coffee"]', '["Meenakshi Amman Temple","Thirumalai Nayak Palace","Gandhi Memorial Museum","Alagar Kovil"]', 9.9252, 78.1198, 8.9, TRUE),

('Ooty', 'Tamil Nadu', 'Ooty (Udhagamandalam), the Queen of Hill Stations, sits at 2,240 meters in the Nilgiri Hills. The charming Nilgiri Mountain Railway (a UNESCO World Heritage toy train) winds through tea, coffee, and eucalyptus plantations. Ooty Lake, the Botanical Gardens with a 650-year-old fossilized tree, and the rose garden are iconic sights.', 'Queen of Hill Stations with toy train rides through Nilgiri tea gardens.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Ooty_lake.jpg/1280px-Ooty_lake.jpg', 'SUMMER,ALL_SEASON', 5000, 'Hill Station & Nature', '["Ooty Varkey","Toda Tribal Sweets","Nilgiri Tea","Homemade Chocolate","Finger Chips"]', '["Nilgiri Mountain Railway","Ooty Botanical Gardens","Doddabetta Peak","Pykara Lake"]', 11.4102, 76.6950, 8.7, FALSE),

('Mahabalipuram', 'Tamil Nadu', 'Mahabalipuram (Mamallapuram) is a UNESCO World Heritage town on the Coromandel Coast south of Chennai. This ancient Pallava port city contains some of the finest rock-cut cave temples, monolithic rathas, and open-air reliefs in India. Shore Temple, one of the oldest structural stone temples in South India, stands at the sea edge.', 'Ancient UNESCO shore temples meeting golden beaches.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Shore_Temple_Mahabalipuram.jpg/1280px-Shore_Temple_Mahabalipuram.jpg', 'ALL_SEASON', 4000, 'Heritage & Beach', '["Prawn Koliwada","Shore Fish Fry","Crab Masala","Idli Sambar","Filter Coffee"]', '["Shore Temple","Arjuna Penance","Five Rathas","Tiger Cave"]', 12.6169, 80.1927, 8.6, FALSE),

-- WEST BENGAL
('Darjeeling', 'West Bengal', 'Darjeeling, the Queen of the Himalayas, is famous worldwide for its tea. The iconic Darjeeling Himalayan Railway toy train, a UNESCO World Heritage Site, winds through misty tea gardens with views of Kangchenjunga. Tiger Hill at sunrise offers a golden view of Kangchenjunga, the worlds third highest peak.', 'Misty tea gardens and Himalayan toy train with Kangchenjunga views.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Darjeeling_Himalayan_Railway.jpg/1280px-Darjeeling_Himalayan_Railway.jpg', 'SUMMER,ALL_SEASON', 5000, 'Hill Station & Tea Culture', '["Darjeeling First Flush Tea","Momos","Thukpa","Gundruk Soup","Sel Roti"]', '["Tiger Hill Sunrise","Batasia Loop","Happy Valley Tea Estate","Peace Pagoda"]', 27.0360, 88.2627, 9.0, TRUE),

-- MAHARASHTRA
('Mumbai', 'Maharashtra', 'Mumbai, the City of Dreams, is a teeming megapolis that never sleeps. From the iconic Gateway of India and the historic Taj Mahal Palace Hotel to Bollywood film studios, Marine Drive, and the street food of Mohammed Ali Road, Mumbai is an assault on all the senses in the best possible way.', 'India city of dreams — Bollywood, sea face, and street food.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Gateway_of_India_Mumbai.jpg/1280px-Gateway_of_India_Mumbai.jpg', 'ALL_SEASON', 8000, 'City & Culture', '["Vada Pav","Pav Bhaji","Bhel Puri","Bombay Duck Fry","Kulfi"]', '["Gateway of India","Elephanta Caves","Marine Drive","Sanjay Gandhi National Park"]', 18.9388, 72.8354, 9.2, TRUE),

('Lonavala', 'Maharashtra', 'Lonavala is a popular hill station in the Sahyadri mountain range, just 65 km from Pune. Famous for its lush green valleys, misty waterfalls, and the iconic Bhushi Dam that overflows dramatically during monsoon, it is a beloved weekend escape. The Rajmachi Fort and Karla Caves add a historical dimension.', 'Misty Sahyadri hill station famous for chikki and monsoon waterfalls.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Lonavala_green_hills.jpg/1280px-Lonavala_green_hills.jpg', 'MONSOON,ALL_SEASON', 4000, 'Hill Station & Waterfalls', '["Chikki","Fudge","Corn Bhakri","Zunka Bhakar","Masala Milk"]', '["Bhushi Dam","Rajmachi Fort","Karla Caves","Tiger Point Viewpoint"]', 18.7546, 73.4062, 8.5, FALSE),

-- KARNATAKA
('Coorg', 'Karnataka', 'Coorg (Kodagu) is a misty, mountainous district in Karnataka known as the Scotland of India. Rolling hills blanketed in coffee and spice plantations, gushing waterfalls, and a unique warrior culture make it one of South Indias most beloved destinations. Abbey Falls and Raja Seat viewpoint are highlights.', 'Scotland of India — coffee hills, waterfalls, and warrior culture.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Coorg_Coffee_Plantation.jpg/1280px-Coorg_Coffee_Plantation.jpg', 'MONSOON,ALL_SEASON', 6000, 'Nature & Coffee Tourism', '["Pandi Curry","Kadambuttu","Coorg Pork","Filter Coffee","Bamboo Shoot Curry"]', '["Abbey Falls","Raja Seat","Namdroling Monastery","Irupu Falls(88km)"]', 12.3375, 75.8069, 8.8, TRUE),

('Hampi', 'Karnataka', 'Hampi is the ruined capital of the once-mighty Vijayanagara Empire, spread across an otherworldly landscape of granite boulders and banana plantations. The UNESCO World Heritage Site contains over 1,600 surviving remains, including the stunning Virupaksha Temple, Vittala Temple with its famous stone chariot, and the Queens Bath.', 'Ancient empire ruins amid surreal boulder landscapes — a UNESCO site.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Stone_Chariot_Hampi.jpg/1280px-Stone_Chariot_Hampi.jpg', 'WINTER,ALL_SEASON', 3500, 'Heritage & Archaeology', '["Jolada Rotti","Badami Holige","Masala Dosa","Bisi Bele Bath","Sugarcane Juice"]', '["Virupaksha Temple","Vittala Temple Stone Chariot","Queens Bath","Matanga Hill Sunrise"]', 15.3350, 76.4600, 9.1, TRUE),

-- JAMMU & KASHMIR
('Srinagar', 'Jammu and Kashmir', 'Srinagar, the summer capital of Jammu and Kashmir, is a city of legendary beauty set on the shores of Dal Lake. Colorful shikaras glide past floating vegetable markets and ornate houseboats. The magnificent Mughal gardens — Shalimar Bagh, Nishat Bagh — and the old city bazaars make Srinagar one of Indias most exotic destinations.', 'Paradise on earth — Dal Lake houseboats and Mughal gardens.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Dal_Lake_Srinagar.jpg/1280px-Dal_Lake_Srinagar.jpg', 'SUMMER,ALL_SEASON', 7500, 'Romantic & Cultural', '["Rogan Josh","Dum Aloo","Wazwan Thali","Kahwa Tea","Sheermal"]', '["Dal Lake Shikara Ride","Shalimar Bagh","Nishat Bagh","Shankaracharya Temple"]', 34.0837, 74.7973, 9.2, TRUE),

-- GUJARAT
('Rann of Kutch', 'Gujarat', 'The Rann of Kutch is one of the largest salt marshes in the world, stretching endlessly under an open sky. During the Rann Utsav festival (November to March), the white salt desert under the full moon is a surreal, otherworldly experience. The region is also rich in tribal crafts, including Kutchi embroidery and mirror work.', 'The worlds largest salt marsh glowing silver under the full moon.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Rann_of_Kutch_White_Desert.jpg/1280px-Rann_of_Kutch_White_Desert.jpg', 'WINTER', 5000, 'Cultural & Unique Landscape', '["Dabeli","Khichdi Kadhi","Kutchi Bhajia","Undhiyu","Basundi"]', '["White Rann","Kalo Dungar (Black Hill)","Dholavira Archaeological Site","Mandvi Beach"]', 23.7333, 69.8500, 9.0, TRUE);
